# Generated by Django 4.1.7 on 2023-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_address_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="type",
            field=models.CharField(
                choices=[("Work address", "Work"), ("Home address", "Home")],
                max_length=150,
            ),
        ),
    ]
