# Generated by Django 4.1.7 on 2023-03-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_book_review_id_review_book_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="genre_name",
            new_name="name",
        ),
    ]
