# Generated by Django 4.1.7 on 2023-03-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_genre_name_genre_name"),
        ("feature", "0002_alter_cart_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="book_id",
            field=models.ManyToManyField(blank=True, to="product.book"),
        ),
    ]
